// Functions to work with languages and language codes

const languageCode = (name: string): string =>
  // returns the language code from the language's full name
  Object.keys(languageNames).find((key) => languageNames[key] === name) || name

const languageName = (code: string) =>
  // returns the language name from the language's code
  languageNames[code] || code

// IETF language codes https://en.wikipedia.org/wiki/IETF_language_tag
// with additions
const languageNames: { [index: string]: any } = {
  '': 'All languages',
  af: 'Afrikaans',
  am: 'Amharic',
  ar: 'Arabic',
  arn: 'Mapudungun',
  as: 'Assamese',
  az: 'Azeri',
  ba: 'Bashkir',
  be: 'Belarusian',
  bg: 'Bulgarian',
  bn: 'Bengali',
  bo: 'Tibetan',
  br: 'Breton',
  bs: 'Bosnian',
  ca: 'Catalan',
  co: 'Corsican',
  cs: 'Czech',
  cy: 'Welsh',
  da: 'Danish',
  de: 'German',
  dr: 'Dari',
  dsb: 'Lower Sorbian',
  dv: 'Divehi',
  el: 'Greek',
  en: 'English',
  es: 'Spanish',
  'es-419': 'Latin-american Spanish',
  et: 'Estonian',
  eu: 'Basque',
  fa: 'Persian',
  fi: 'Finnish',
  fil: 'Filipino',
  fo: 'Faroese',
  fr: 'French',
  fy: 'Frisian',
  ga: 'Irish',
  gd: 'Scottish Gaelic',
  gl: 'Galician',
  gsw: 'Alsatian',
  gu: 'Gujarati',
  ha: 'Hausa',
  he: 'Hebrew',
  hi: 'Hindi',
  hr: 'Croatian',
  hsb: 'Upper Sorbian',
  hu: 'Hungarian',
  hy: 'Armenian',
  id: 'Indonesian',
  ig: 'Igbo',
  ii: 'Yi',
  is: 'Icelandic',
  it: 'Italian',
  iu: 'Inuktitut',
  ja: 'Japanese',
  ka: 'Georgian',
  kk: 'Kazakh',
  kl: 'Greenlandic',
  km: 'Khmer',
  kn: 'Kannada',
  ko: 'Korean',
  kok: 'Konkani',
  ky: 'Kyrgyz',
  lb: 'Luxembourgish',
  lo: 'Lao',
  lt: 'Lithuanian',
  lv: 'Latvian',
  mi: 'Maori',
  mk: 'Macedonian',
  ml: 'Malayalam',
  mn: 'Mongolian',
  moh: 'Mohawk',
  mr: 'Marathi',
  ms: 'Malay',
  mt: 'Maltese',
  my: 'Burmese',
  nb: 'Norwegian (Bokmål)',
  ne: 'Nepali',
  nl: 'Dutch',
  nn: 'Norwegian (Nynorsk)',
  no: 'Norwegian',
  nso: 'Sesotho',
  oc: 'Occitan',
  or: 'Oriya',
  pa: 'Punjabi',
  'pa-pk': 'Punjabi (Pakistan)',
  pl: 'Polish',
  prs: 'Dari',
  ps: 'Pashto',
  pt: 'Portuguese',
  qut: "K'iche",
  quz: 'Quechua',
  rm: 'Romansh',
  ro: 'Romanian',
  ru: 'Russian',
  rw: 'Kinyarwanda',
  sa: 'Sanskrit',
  sah: 'Yakut',
  se: 'Sami (Northern)',
  si: 'Sinhala',
  sk: 'Slovak',
  sl: 'Slovenian',
  sma: 'Sami (Southern)',
  smj: 'Sami (Lule)',
  smn: 'Sami (Inari)',
  sms: 'Sami (Skolt)',
  so: 'Somali',
  sq: 'Albanian',
  sr: 'Serbian',
  sv: 'Swedish',
  sw: 'Kiswahili',
  syr: 'Syriac',
  ta: 'Tamil',
  te: 'Telugu',
  tg: 'Tajik',
  th: 'Thai',
  tk: 'Turkmen',
  tn: 'Setswana',
  tr: 'Turkish',
  tt: 'Tatar',
  tzm: 'Tamazight',
  ug: 'Uyghur',
  uk: 'Ukrainian',
  ur: 'Urdu',
  uz: 'Uzbek',
  vi: 'Vietnamese',
  wo: 'Wolof',
  xh: 'isiXhosa',
  yi: 'Yiddish',
  yo: 'Yoruba',
  zh: 'Chinese',
  'zh-hk': 'Chinese (Hong-Kong)',
  'zh-tw': 'Chinese (Taiwan)',
  zu: 'isiZulu',
}

export { languageCode, languageName }
